### ISSUE TITLE
Add support for JSON files

### ISSUE THREAD

**Issue by muhammedabad** [tomoh1r/ansible-vault#28]
I have the need to occasionally encrypt/decrypt a JSON file that is part of my ansible project.  Not sure if this is something that would be a worthwhile addition or be of interest to many users, but I made some changes to add support for JSON files and thought of sharing them.

See #27 for more info.

**Comment by tomoh1r** [comment]
https://github.com/tomoh1r/ansible-vault/wiki/sample#json
Please consider to use load_raw/dump_raw method and wrap with json module.
