### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by regiwils** [tomoh1r/ansible-vault#4]
Please provide contact/information on reporting security issues for Ansible-vault

**Comment by tomoh1r** [comment]
Sorry for too late response. I fix it, and release ver 1.0.5.

**Comment by regiwils** [comment]
Thanks for the confirmation.


Regina Wilson
Engineer. Research
regiwils@cisco.com<mailto:regiwils@cisco.com>




[cid:CFA14CB5-B7B2-4FF7-8313-22D495F607D5@vrt.sourcefire.com]

On Sep 13, 2017, at 9:28 AM, Tomohiro Nakamura <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://github.com/tomoh1r/ansible-vault/issues/4>.
